//Even Fibonacci numbers    
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

//program result:
//The sum of all even Fibonacci numbers below 4000000 is 4613732
//Total time = 0.000021 seconds

//c code:


#include <sys/time.h>
#include <stdio.h>


int show_sum_fibonacci_evens(int limit)
{
    //Finding the sum of all even Fibonacci number
    //below limit.
    
    //definitions
    int aux, fibo1, fibo2, sum_even_fibo;
    
    //initialization
    fibo1=1;
    fibo2=2;    
    sum_even_fibo=2;//first even
    
    //validation
    if (limit <=1){
        printf("\n\n Invalid limit");
        return 1;
    }
    
    
    while( fibo2 <= limit ) {     
        aux=fibo1+fibo2;
        fibo1=fibo2;
        fibo2=aux;
        //accumulate if it is even
        if (fibo2 % 2==0)
            sum_even_fibo += fibo2;
    }

    printf("\n\n The sum of all even Fibonacci numbers below %d is %d", limit, sum_even_fibo);

    return 0;

}    



int main(){
    int maxlimit;
    struct timeval  tv1, tv2;
    
    //start time
    gettimeofday(&tv1, NULL);
    
    maxlimit=4000000;

    //find the solution
    show_sum_fibonacci_evens(maxlimit);
 
    //stop time
    gettimeofday(&tv2, NULL);

    printf  ("\n\n Total time = %f seconds\n",
            (double) (tv2.tv_usec - tv1.tv_usec) / 1000000 +
            (double) (tv2.tv_sec - tv1.tv_sec));
    
    return 0;
    
}
